### ISSUE TITLE
Функции опроса кнопок?

### ISSUE THREAD

**Issue by NaOsi** [Volodya-B1tik/xy_table#1]
Сегодня общался с "создателем" стола. он сказал что его зовут ЕББ_бот  xD.
В этих функциях, похоже и ведется опрос нажатых кнопок:
https://github.com/Volodya-B1tik/xy_table/blob/main/ebb_motion.py#L725-L770

**Comment by NaOsi** [comment]
А ниже уже, похоже, функция установки в ноль! =) 
https://github.com/Volodya-B1tik/xy_table/blob/main/ebb_motion.py#L773

**Comment by Volodya-B1tik** [comment]
Создал контейнер с нужным версиями и библиотеками. Скрипт управление запускается и выполняется, но стол не двигается. Это может возникать 

1.  Скрипт взаимодействия с компортом напсан под винду
2.  Докер мешает работу с портом (хотя врядли т.к я прокидываю юсб шину полностью)
